// Generated by CoffeeScript 1.9.0
(function() {
  var Branch, Query, f, instanceid, _;

  _ = require("lodash");

  Query = require("./query");

  f = require("./functions");

  instanceid = 0;

  Branch = (function() {
    function Branch(parent, name) {
      instanceid += 1;
      this.state = _(parent.state).clone();
      this.state.id = "branch:" + instanceid;
      this.state.branch = name;
      this.state.parent = parent;
      this.state.children = {};
      this.state.commited = {};
      this.state.dirty = {};
      this.state.changes = {};
    }

    Branch.prototype.branch = function() {
      return this.state.branch;
    };

    Branch.prototype.onerr = function(fn) {
      f.onerr(this, fn);
      return this;
    };

    Branch.prototype.onread = function(fn) {
      f.onread(this, fn);
      return this;
    };

    Branch.prototype.onstored = function(fn) {
      f.onstored(this, fn);
      return this;
    };

    Branch.prototype.filename = function() {
      return f.filename(this);
    };

    Branch.prototype.load = function(fn) {
      return f.load(this, fn);
    };

    Branch.prototype.oblit = function() {
      return f.oblit(this);
    };

    Branch.prototype.close = function() {
      return f.close(this);
    };

    Branch.prototype.fork = function(name) {
      return f.fork(this, name);
    };

    Branch.prototype.merge = function() {
      return f.merge(this);
    };

    Branch.prototype.changed = function() {
      return f.changed(this);
    };

    Branch.prototype.discard = function() {
      return f.discard(this);
    };

    Branch.prototype.query = function() {
      return new Query(this);
    };

    Branch.prototype.set = function(itms) {
      return f.set(this, itms);
    };

    Branch.prototype.remove = function(keys) {
      return f.remove(this, keys);
    };

    Branch.prototype.store = function() {
      return f.store(this);
    };

    Branch.prototype.inspect = function() {
      return f.inspect(this, this.state.dirty);
    };

    return Branch;

  })();

  module.exports = Branch;

}).call(this);
