// Generated by CoffeeScript 1.7.1
(function() {
  var Branch, Query, f, _;

  _ = require("underscore");

  Query = require("./query");

  f = require("./functions");

  Branch = (function() {
    function Branch(state) {
      this.state = _(state).clone();
    }

    Branch.prototype.init = function(name, parent) {
      this.state.branch = name;
      this.state.parent = parent;
      this.state.children = {};
      this.state.commited = {};
      this.state.dirty = {};
      this.state.changes = {};
      return this;
    };

    Branch.prototype.branch = function() {
      return this.state.branch;
    };

    Branch.prototype.onerr = function(fn) {
      f.onerr(this, fn);
      return this;
    };

    Branch.prototype.ondata = function(fn) {
      f.ondata(this, fn);
      return this;
    };

    Branch.prototype.onstored = function(fn) {
      f.onstored(this, fn);
      return this;
    };

    Branch.prototype.filename = function() {
      return f.filename(this);
    };

    Branch.prototype.load = function() {
      return f.load(this);
    };

    Branch.prototype.oblit = function() {
      return f.oblit(this);
    };

    Branch.prototype.close = function() {
      return f.close(this);
    };

    Branch.prototype.fork = function(name) {
      return f.fork(this, name);
    };

    Branch.prototype.merge = function() {
      return f.merge(this);
    };

    Branch.prototype.changed = function() {
      return f.changed(this);
    };

    Branch.prototype.discard = function() {
      return f.discard(this);
    };

    Branch.prototype.commit = function() {
      return f.commit(this);
    };

    Branch.prototype.query = function() {
      return new Query(this);
    };

    Branch.prototype.set = function(itms) {
      return f.set(this, itms);
    };

    Branch.prototype.remove = function(keys) {
      return f.remove(this, keys);
    };

    Branch.prototype.store = function() {
      return f.store(new Branch(this.state));
    };

    return Branch;

  })();

  module.exports = Branch;

}).call(this);
